import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className='flex items-center justify-between px-4 bg-gray-500'>
          <Link className='font-bold bg-gray-600' href="/">Logo</Link>
          <ul className='flex items-center gap-3 bg-blue-400'>
            <li><Link href="/about" className='bg-red-400'>About Page</Link></li>
            <li><Link href="/about/company">Company Page</Link></li>
          </ul>
        </div>
        {children}</body>
    </html>
  )
}
